name: Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: deno test --no-run src/**/*.ts
      - run: deno lint
      - run: deno fmt --check
      - run: deno test --allow-env
        env:
          TOKEN: dummy-token
          BOT_TOKEN: dummy-bot-token
          POST_CHANNEL: dummy-post-channel

